---
title: ResultElf - TEST
timezone: Europe/Helsinki
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
description: From Big Data to Analysis and Modeling  to Insight Identification to
  Action to Results
baseurl:
url: https://www.resultelf.com
google_analytics: UA-7870337-1
plugins:
- jekyll-sitemap
- jekyll-feed
feed:
  path: "/1/feed.xml"
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
