---
title: ResultElf
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: From Big Data to Analysis and Modeling  to Insight Identification to
  Action to Results
baseurl:
url: https://www.resultelf.com
twitter_username: jekyllrb
github_username: jekyll
google_analytics: UA-7870337-1
plugins:
- jekyll-sitemap
- jekyll-feed

feed:
  path: /1/feed.xml

exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
